### ISSUE TITLE
Password is not echoed: 'Not a tty'

### ISSUE THREAD

**Issue by nstrelow** [hassio-addons/addon-lovelace-migration#6]
# Problem/Motivation

>  Lovelace Migration erroring because of 'Not a tty'

## Expected behavior

> Lovelace Migration finishing everything and writing the output file

## Actual behavior

> Starting lovelace migration for the first time. Throws me following error:

```
INFO: Output file is set to: /config/ui-lovelace.yaml
TRACE: hass.config.has_value: init_commands
TRACE: hass.jq.has_value: /data/options.json .init_commands
TRACE: hass.jq: /data/options.json .init_commands | if (. == {} or . == []) then empty else . end // empty
TRACE: hass.has_value: 
/usr/lib/python3.6/getpass.py:91: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
Enter password: Traceback (most recent call last):
  File "/usr/lib/python3.6/getpass.py", line 69, in unix_getpass
    old = termios.tcgetattr(fd)     # a copy to save
termios.error: (25, 'Not a tty')
```

## Steps to reproduce

> I am using hass.io installed on a RPi3 with docker.

**Comment by frenck** [comment]
@nstrelow It seems like the Supervisor released yesterday (129) contained a bug. Please upgrade to Supervisor 130, which probably fixes this issue.

**Comment by nstrelow** [comment]
Worked like a charm, thanks for sorting that out.

**Comment by frenck** [comment]
Glad to hear that!
