### ISSUE TITLE
Problem in migrate

### ISSUE THREAD

**Issue by lscosta90br** [hassio-addons/addon-lovelace-migration#7]
When I try to migrate the following error appears:

  File "/root/lovelace_migrate.py", line 277, in from_group_config
    card = Lovelace.Card.from_config(entity)
  File "/root/lovelace_migrate.py", line 234, in from_config
    return cls.from_config(config)
  File "/root/lovelace_migrate.py", line 229, in from_config
    return super().from_config(config)
  File "/root/lovelace_migrate.py", line 129, in from_config
[cmd] /usr/bin/run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.
 
 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.

# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by tjorim** [comment]
Please provide some more info like config, system, versions...
This might actually be an issue with the script used and not this add-on.

To test if the issue is with this add-on, go here: https://github.com/dale3h/python-lovelace
And try to run it locally with your configuration.yaml on a pc.
If it still fails, report the issue over there.
